package info.maaskant.wmsnotes.model

/**
 * @property requestId An identifier to trace the request.
 * @property commands All commands and whether they were executed successfully.
 * @property newEvents All events generated by the execution of the commands.
 */
data class CommandResult(
        val requestId: Int,
        val commands: List<Pair<Command, Boolean>>,
        val newEvents: List<Event>
) {
    val allSuccessful = commands.asSequence()
            .map { it.second }
            .all { it }
}
